import pyautogui
import pandas as pd
import time
x=1
#time.sleep(5*x)
#print(pyautogui.position()) #--> mostra coordenada do mouse
email = "pipipopo@lalal.com" # input("Escreva seu email: ")
senha = "12345678" # input("Escreva sua senha: ")
pyautogui.hotkey("win","r")
pyautogui.write("cmd")
pyautogui.press("enter")
time.sleep(0.5*x)
pyautogui.write("start chrome.exe")
time.sleep(0.5*x)
pyautogui.press("enter")
time.sleep(2*x)
pyautogui.hotkey("alt","tab")
pyautogui.hotkey("alt","f4")
pyautogui.write("https://dlp.hashtagtreinamentos.com/python/intensivao/login") 
pyautogui.press("enter")
time.sleep(2*x)
pyautogui.press("tab")
pyautogui.write(email)
pyautogui.press("tab")
pyautogui.write(senha)
time.sleep(1*x)
pyautogui.press("enter")
time.sleep(2*x)
df = pd.read_csv("C:/Users/User/Desktop/PROJETO/py/ex01/produtos.csv")

for linha in df.index:
    #codigo = df.loc[linha,"codigo"]
    pyautogui.click(870,237)
    pyautogui.write(str(df.loc[linha,"codigo"]))
    time.sleep(0.5*x)
    pyautogui.press("tab")
    pyautogui.write(str(df.loc[linha,"marca"]))
    time.sleep(0.5*x)
    pyautogui.press("tab")
    pyautogui.write(str(df.loc[linha,"tipo"]))
    time.sleep(0.5*x)
    pyautogui.press("tab")
    pyautogui.write(str(df.loc[linha,"categoria"]))
    time.sleep(0.5*x)
    pyautogui.press("tab")
    pyautogui.write(str(df.loc[linha,"preco_unitario"]))
    time.sleep(0.5*x)
    pyautogui.press("tab")
    pyautogui.write(str(df.loc[linha,"custo"]))
    time.sleep(0.5*x)
    pyautogui.press("tab")
    obs = str(df.loc[linha,"obs"])
    if obs != "nan":
        pyautogui.write(obs)
    time.sleep(0.5*x)
    pyautogui.press("tab")
    pyautogui.press("enter")
#pyautogui.drag --> arrasta o mouse
#time.sleep(1*x)
#pyautogui.click(868,330)
#pyautogui.write(email)
#pyautogui.click(865,405)
#pyautogui.write(senha)
#time.sleep(1*x)
#pyautogui.click(1092,455)
#time.sleep(4*x)
#pyautogui.hotkey("alt","f4") 
#print(df)
